# Generated by Django 2.2.3 on 2019-07-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'deleted')},
        ),
    ]
