# Generated by Django 2.2.3 on 2019-07-21 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0003_auto_20190721_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(choices=[('royal', 'Royal'), ('grand', 'Grand'), ('ambassador', 'Ambassador')], default='grand', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('name', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'room', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'hotel', 'deleted')},
        ),
    ]
